/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sh.now.arifikhsanudin.rentalin_netbeans.screeen.home;


import sh.now.arifikhsanudin.rentalin_netbeans.repository.CarRepositoryImpl;
import sh.now.arifikhsanudin.rentalin_netbeans.repository.RentalRepositoryImpl;
import sh.now.arifikhsanudin.rentalin_netbeans.repository.UserRepositoryImpl;
import sh.now.arifikhsanudin.rentalin_netbeans.repository.contract.CarRepository;
import sh.now.arifikhsanudin.rentalin_netbeans.repository.contract.RentalRepository;
import sh.now.arifikhsanudin.rentalin_netbeans.repository.contract.UserRepository;
import sh.now.arifikhsanudin.rentalin_netbeans.screeen.car.CarScreen;
import sh.now.arifikhsanudin.rentalin_netbeans.screeen.contract.ScreenInterface;
import sh.now.arifikhsanudin.rentalin_netbeans.screeen.rental.RentalScreen;
import sh.now.arifikhsanudin.rentalin_netbeans.screeen.user.UserScreen;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 * @author arifikhsanudin
 */
public class HomeScreen extends javax.swing.JFrame implements ScreenInterface {
    UserRepository userRepository = new UserRepositoryImpl();
    CarRepository carRepository = new CarRepositoryImpl();
    RentalRepository rentalRepository = new RentalRepositoryImpl();

    /**
     * Creates new form NewJFrame
     */
    public HomeScreen() {
        initComponents();
        populateView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRental = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCar = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonUserDelete = new javax.swing.JButton();
        buttonUserView = new javax.swing.JButton();
        buttonUserAdd = new javax.swing.JButton();
        buttonCarAdd = new javax.swing.JButton();
        buttonCarView = new javax.swing.JButton();
        buttonCarDelete = new javax.swing.JButton();
        buttonRentalDelete = new javax.swing.JButton();
        buttonRentalView = new javax.swing.JButton();
        buttonRentalAdd = new javax.swing.JButton();
        refreshUser = new javax.swing.JButton();
        refreshCar = new javax.swing.JButton();
        refreshRental = new javax.swing.JButton();
        refreshAll = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Gilroy Light", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 102, 255));
        labelTitle.setText("Rentalin Admin");

        tableRental.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Id", "Nama Penyewa", "Nama Mobil", "Tanggal Sewa", "Tanngal Kembali"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRental);

        tableCar.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Id", "Nama", "Nomor Polisi", "Harga Per Jam"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCar);

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Id", "Nama", "Alamat", "Nomor HP"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableUser);

        jLabel2.setFont(new java.awt.Font("Gilroy Light", 0, 18)); // NOI18N
        jLabel2.setText("Penyewaan");

        jLabel4.setFont(new java.awt.Font("Gilroy Light", 0, 18)); // NOI18N
        jLabel4.setText("Mobil");

        jLabel5.setFont(new java.awt.Font("Gilroy Light", 0, 18)); // NOI18N
        jLabel5.setText("Pelanggan");

        buttonUserDelete.setText("Hapus");
        buttonUserDelete.setEnabled(false);
        buttonUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserDeleteActionPerformed(evt);
            }
        });

        buttonUserView.setText("Lihat");
        buttonUserView.setEnabled(false);
        buttonUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserViewActionPerformed(evt);
            }
        });

        buttonUserAdd.setText("Tambah");
        buttonUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserAddActionPerformed(evt);
            }
        });

        buttonCarAdd.setText("Tambah");
        buttonCarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarAddActionPerformed(evt);
            }
        });

        buttonCarView.setText("Lihat");
        buttonCarView.setEnabled(false);
        buttonCarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarViewActionPerformed(evt);
            }
        });

        buttonCarDelete.setText("Hapus");
        buttonCarDelete.setEnabled(false);
        buttonCarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarDeleteActionPerformed(evt);
            }
        });

        buttonRentalDelete.setText("Hapus");
        buttonRentalDelete.setEnabled(false);
        buttonRentalDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentalDeleteActionPerformed(evt);
            }
        });

        buttonRentalView.setText("Lihat");
        buttonRentalView.setEnabled(false);
        buttonRentalView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentalViewActionPerformed(evt);
            }
        });

        buttonRentalAdd.setText("Tambah");
        buttonRentalAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRentalAddActionPerformed(evt);
            }
        });

        refreshUser.setText("Refresh");
        refreshUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshUserActionPerformed(evt);
            }
        });

        refreshCar.setText("Refresh");
        refreshCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCarActionPerformed(evt);
            }
        });

        refreshRental.setText("Refresh");
        refreshRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRentalActionPerformed(evt);
            }
        });

        refreshAll.setText("Refresh Semua");
        refreshAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAllActionPerformed(evt);
            }
        });

        buttonExit.setText("Keluar");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(refreshAll)
                                                                .addGap(25, 25, 25)
                                                                .addComponent(refreshRental)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(buttonRentalAdd)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(buttonRentalView)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(buttonRentalDelete))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(buttonCarAdd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonCarView)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonCarDelete)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)
                                                .addGap(277, 277, 277))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(refreshCar))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(buttonUserAdd)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(buttonUserView)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(buttonUserDelete))
                                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(refreshUser))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(labelTitle)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(buttonExit)))
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelTitle)
                                        .addComponent(buttonExit))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(buttonRentalDelete)
                                        .addComponent(buttonRentalView)
                                        .addComponent(buttonRentalAdd)
                                        .addComponent(refreshAll)
                                        .addComponent(refreshRental))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(buttonCarDelete)
                                        .addComponent(buttonCarView)
                                        .addComponent(buttonCarAdd)
                                        .addComponent(buttonUserDelete)
                                        .addComponent(buttonUserView)
                                        .addComponent(buttonUserAdd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(refreshCar))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(refreshUser)))
                                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserDeleteActionPerformed
        Integer userId = Integer.parseInt(tableUser.getValueAt(tableUser.getSelectedRow(), 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Hapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            userRepository.delete(userId);
            populateTableUser();
        }
    }//GEN-LAST:event_buttonUserDeleteActionPerformed

    private void buttonCarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarDeleteActionPerformed
        Integer carId = Integer.parseInt(tableCar.getValueAt(tableCar.getSelectedRow(), 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Hapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            carRepository.delete(carId);
            populateTableCar();
        }
    }//GEN-LAST:event_buttonCarDeleteActionPerformed

    private void buttonRentalDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentalDeleteActionPerformed
        Integer rentalId = Integer.parseInt(tableRental.getValueAt(tableRental.getSelectedRow(), 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Hapus?", "Peringatan", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            rentalRepository.delete(rentalId);
            populateTableRental();
        }
    }//GEN-LAST:event_buttonRentalDeleteActionPerformed

    private void buttonUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserAddActionPerformed
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_buttonUserAddActionPerformed

    private void refreshUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshUserActionPerformed
        populateTableUser();
    }//GEN-LAST:event_refreshUserActionPerformed

    private void buttonUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserViewActionPerformed
        Integer userId = Integer.parseInt(tableUser.getValueAt(tableUser.getSelectedRow(), 0).toString());
        new UserScreen(userId).setVisible(true);
    }//GEN-LAST:event_buttonUserViewActionPerformed

    private void buttonCarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarAddActionPerformed
        new CarScreen().setVisible(true);
    }//GEN-LAST:event_buttonCarAddActionPerformed

    private void buttonCarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarViewActionPerformed
        Integer carId = Integer.parseInt(tableCar.getValueAt(tableCar.getSelectedRow(), 0).toString());
        new CarScreen(carId).setVisible(true);
    }//GEN-LAST:event_buttonCarViewActionPerformed

    private void refreshCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCarActionPerformed
        populateTableCar();
    }//GEN-LAST:event_refreshCarActionPerformed

    private void refreshAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAllActionPerformed
        populateView();
    }//GEN-LAST:event_refreshAllActionPerformed

    private void refreshRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRentalActionPerformed
        populateTableRental();
    }//GEN-LAST:event_refreshRentalActionPerformed

    private void buttonRentalAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentalAddActionPerformed
        new RentalScreen().setVisible(true);
    }//GEN-LAST:event_buttonRentalAddActionPerformed

    private void buttonRentalViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRentalViewActionPerformed
        Integer rentalId = Integer.parseInt(tableRental.getValueAt(tableRental.getSelectedRow(), 0).toString());
        new RentalScreen(rentalId).setVisible(true);
    }//GEN-LAST:event_buttonRentalViewActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Keluar?", "Peringatan", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCarAdd;
    private javax.swing.JButton buttonCarDelete;
    private javax.swing.JButton buttonCarView;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonRentalAdd;
    private javax.swing.JButton buttonRentalDelete;
    private javax.swing.JButton buttonRentalView;
    private javax.swing.JButton buttonUserAdd;
    private javax.swing.JButton buttonUserDelete;
    private javax.swing.JButton buttonUserView;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JButton refreshAll;
    private javax.swing.JButton refreshCar;
    private javax.swing.JButton refreshRental;
    private javax.swing.JButton refreshUser;
    private javax.swing.JTable tableCar;
    private javax.swing.JTable tableRental;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void populateView() {
        populateTableUser();
        populateTableCar();
        populateTableRental();
    }

    private void populateTableUser() {
        buttonUserView.setEnabled(false);
        buttonUserDelete.setEnabled(false);

        DefaultTableModel tableModelUser = (DefaultTableModel) tableUser.getModel();
        tableModelUser.setRowCount(0);
        userRepository.getUsers().forEach(user -> {
            tableModelUser.addRow(new Object[]{user.getId(), user.getName(), user.getAddress(), user.getPhoneNumber()});
        });

        tableUser.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                buttonUserView.setEnabled(true);
                buttonUserDelete.setEnabled(true);
            }

            @Override
            public void mousePressed(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseReleased(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseEntered(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseExited(MouseEvent mouseEvent) {

            }
        });
    }

    private void populateTableCar() {
        buttonCarView.setEnabled(false);
        buttonCarDelete.setEnabled(false);

        DefaultTableModel tableModelCar = (DefaultTableModel) tableCar.getModel();
        tableModelCar.setRowCount(0);
        carRepository.getCars().forEach(car -> {
            tableModelCar.addRow(new Object[]{car.getId(), car.getName(), car.getPoliceNumber(), car.getPricePerHour()});
        });

        tableCar.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                buttonCarView.setEnabled(true);
                buttonCarDelete.setEnabled(true);
            }

            @Override
            public void mousePressed(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseReleased(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseEntered(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseExited(MouseEvent mouseEvent) {

            }
        });
    }

    private void populateTableRental() {
        buttonRentalView.setEnabled(false);
        buttonRentalDelete.setEnabled(false);

        DefaultTableModel rentalModelCar = (DefaultTableModel) tableRental.getModel();
        rentalModelCar.setRowCount(0);
        rentalRepository.getRentals().forEach(rental -> {
            rentalModelCar.addRow(new Object[]{rental.getId(), rental.car.getName(), rental.user.getName(), rental.getDateBorrow(), rental.getDateReturn()});
        });

        tableRental.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                buttonRentalView.setEnabled(true);
                buttonRentalDelete.setEnabled(true);
            }

            @Override
            public void mousePressed(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseReleased(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseEntered(MouseEvent mouseEvent) {

            }

            @Override
            public void mouseExited(MouseEvent mouseEvent) {

            }
        });
    }
}